name: color_line_picker
description: This package helps you to create color palette as horizontal list. Able to detech which color picked and returns it.
version: 0.1.0
homepage: https://github.com/imertgul/color_line_picker

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
